PROC IMPORT DATAFILE='/folders/myfolders/Electronic.xlsx'
			OUT=WORK.Electronic
			DBMS=XLSX;
			GETNAMES=YES;
RUN;

PROC PRINT DATA=WORK.Electronic;
RUN;

PROC SQL;
	SELECT PRODUCT, DISCOUNT, SALES*0.05 AS TAX,(PROFIT- CALCULATED TAX) AS NET_PROFIT FORMAT=DOLLAR10.2
	CASE
	WHEN SALES BETWEEN 0 AND 100 THEN 'MEDIUM'
	WHEN SALES BETWEEN 101 AND 200 THEN 'HIGH'
	WHEN SALES BETWEEN 201 AND 300 THEN 'CRITICAL'
	ELSE 'VERY CRITICAL'
	END AS ORDER_PRIORITY2
	FROM ELECTRONIC;
QUIT;
