PROC IMPORT DATAFILE='/folders/myfolders/Electronic.xlsx'
			OUT=WORK.Electronic
			DBMS=XLSX;
			GETNAMES=YES;
RUN;

PROC SQL;
		SELECT PRODUCT,DISCOUNT
		CASE
		WHEN SALES BETWEEN 0 AND 100 THEN 'MEDIUM'
		WHEN SALES BETWEEN 101 AND 200 THEN 'HIGH'
		WHEN SALES BETWEEN 201 AND 300 THEN 'CRITICAL'
		ELSE 'VERY CRITICAL'
		END AS ORDER_PRIORITY1 FROM Electronic;
QUIT;
