PROC IMPORT DATAFILE='/folders/myfolders/Electronic.xlsx'
			OUT=WORK.Electronic
			DBMS=XLSX
			REPLACE;
RUN;
PROC IMPORT DATAFILE='/folders/myfolders/Electronic_CustInfo.xlsx'
			OUT=WORK.ELECTRONIC_CUSTINFO
			DBMS=XLSX;
			GETNAMES=YES;
RUN;
PROC SQL;
	CREATE TABLE INNNER_JOIN_ON
			SELECT * FROM ELECRONIC AS E INNER JOIN ELECTRONIC_CUSTINFO AS C
			ON E.ORDER_ID=C.ORDER_ID;
QUIT;